[package]
name = "wasm_mid"
version = "0.1.0"
authors = ["k <worileqing@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm_std = {path = "../wasm_std"}

[features]
std = ["wasm_std/std"]